### ISSUE TITLE
Hands "jitters" when moving

### ISSUE THREAD

**Issue by marcelfalliere** [oneMillionWorlds/Tamarin#1] opened 2022-03-31 14:30 UTC
Hi @richardTingle,

It's something I've noticed in TamarinBed and in my game.

When moving with the right thumbstick, ie the nausea inducing movement, the hands are offset from the camera. I should make a video, because it's hard to explain... Steps to reproduce :
- start the "moving" examples in Tamarinbed
- look at one hand, let's say the left
- move forward with the right thumbstick, just a little bit
- see that right as we start moving, the left hand is moved to another position too much far away
- release right thumbstick, hands go back to where it should

If you witness this "jitter", that's good. If not I can try to make a video.

Now, how should we proceed ?

https://github.com/oneMillionWorlds/Tamarin/blob/main/src/main/java/com/onemillionworlds/tamarin/vrhands/VRHandsAppState.java#L168

The hands are attached to the rootNode. My first instinct would be to have the hands as a child to the camera, via a CameraNode. Because the hands positions are always relative to the eyes, not the world.

"Forcing" a CameraNode might not fit all use cases though.

What do you think ?

**Comment by richardTingle** [comment] 2022-03-31 17:07
@marcelfalliere yes, I can see that issue. I'll investigate and get back to you. Thanks for reporting

**Comment by richardTingle** [comment] 2022-04-01 12:18
@marcelfalliere I have now fixed the issue you reported and released a new version 1.2.1 (may take an hour or so to appear on maven central). Could you try it and confirm it resolves the jitter problem.

The problem was that during an update cycle first the hands determined their positions (based on the observer position) then later within the same update cycle the observer was moved prior to the final render, leading to the hands being out of position for that frame (and so jittering).

I followed your suggestion and started using the Node based observer rather than the camera based observer (which always felt wrong if I'm honest as its not in any way being used as a camera). This is unfortunately a breaking change but hopefully a small one. During initialisation a node (that is attached to the root node) should be registered as the observer, and then whenever the player is teleporting/walking that node should be moved (or rotated). That means the hands see any updates immediately, not a frame later as you observed.

I have updated the wiki and the Tamarin Test Bed.

**Comment by richardTingle** [comment] 2022-04-01 12:23
(I realise that you suggested a Camera node, but as the observer isn't actually a camera at all just a reference point a regular node does just as well. There are 2 true cameras for the 2 players eyes but they are separate from the observer camera)

**Comment by marcelfalliere** [comment] 2022-04-01 16:04
I'll test that right away and report.

PS: I see you've added a getter for velocity in PoseActionState. I'm implementing a climb feature at the moment, I was looking for that :)

**Comment by richardTingle** [comment] 2022-04-01 16:06
@marcelfalliere Thanks!

Be aware that the velocity is currently in the openVR coordinate space (which is similar to observer space but rotated). That is a known bug and I'll be fixing it shortly

**Comment by marcelfalliere** [comment] 2022-04-01 16:10
Ok, about velocity, I just begun the implementation.

TAmarinTestBed with 1.2.1 works nice, well done ! I will now use 1.2.1 in my game, I'll let you know how it went.

**Closed** 2022-04-01 16:14 UTC

**Comment by marcelfalliere** [comment] 2022-04-01 16:25
Implemented ! I think like that the Tamarin API is more explicit.

```
        Node playerNode = new Node("player");
        Node eyes = new Node();
        eyes.setLocalTranslation(0, Params.PLAYER_HEIGHT, 0);
        playerNode.attachChild(eyes);
        getStateManager().getState(VRAppState.class).setObserver(eyes);
```

Back to climbing ⛰️

**Comment by richardTingle** [comment] 2022-04-01 16:35
Be aware that the observer isn't quite the same as the eyes. 

The observer is the origin of the physical world the human walks around in placed in the game world*. Imagine if you physically walked a meter in your sitting room, your in-game eyes move 1 meter as well. But the observer (the origin) does not (as your application did not request it to). The observer only moves when you change the chunk of real-space that overlaps with game-space.

*I think I'm doing a bad job of explaining that. I think I'll physically place the observer in the moving example so that's a bit clearer

**Comment by marcelfalliere** [comment] 2022-04-01 16:49
I think the observer should move whether you move in real life (ie room-scale games) or with controls (for examples teleport or thumbstick).

Otherwise when you move in your room 1 meter, then with the control, the player will snap back to where the it was before the real world movement.

I mean, for "physical" games (Alyx, Into the radius for examples) that is the way to go. They may be other use cases where that's not the case.

**Comment by marcelfalliere** [comment] 2022-04-01 17:08
> But the observer (the origin) does not (as your application did not request it to). The observer only moves when you change the chunk of real-space that overlaps with game-space.

So I've been reading this sentence over and over, I don't understand it. Can you elaborate, or maybe point to a discussion/article that would clarify ?

Maybe I'm biased, but in all VR game I've tried so far, it seems the general agreement is exactly the opposite : moving your real life neck moves the observer, therefore the origin. Otherwise moving IRL would not move the ingame observer/camera/origin, therefore it would not be a VR game, just a static video ?

Anyway, an example might be à propos to clarify all this :)

**Comment by richardTingle** [comment] 2022-04-01 18:16
I've committed an update to the testbed so that the observer's position in the game world is shown. The thing that's interesting is that if you pier out of your VR headset you'll notice that the observer is always in the same position in the real world but moves about in the game world. 

Personally I think observer is a bad name. I would have called it origin (that part of the API comes from core jmonkey not tamarin).

This feels sensible because the VR headset tells the game where the players eyes are, not the other way round. The game just decides what the offset is between the sitting room and the game; that's what the observer defines

**Comment by marcelfalliere** [comment] 2022-04-02 10:38
Okay, It's a bit clearer.

So if I want to go the other way around, ie, moving the player by moving in the playroom... `vrAppState.getVRViewManager().getLeftCamera().getLocation()` is a good way to get position ?

**Comment by richardTingle** [comment] 2022-04-02 12:25
@marcelfalliere Yes, if you want to know where the player's head is that's a good way to do it

**Comment by richardTingle** [comment] 2022-04-02 14:36
@marcelfalliere I've just released 1.2.2 which has the correct hand velocities that I mentioned. There is a new demo in the test bed (hand velocity example (throwing)) that shows how it can be used to get the hands velocity and rotational velocity. In the demo it uses that to set the starting velocities for thrown stones

**Comment by marcelfalliere** [comment] 2022-04-02 14:50
Okay, I'll take a look, thanks !

I put climbing aside for a while, I'm working on the movement atm. I'm using BetterCharacterControl for the physics ; would you be interested in me making a pull request to integrate this in TamarinTestBed ?

**Comment by richardTingle** [comment] 2022-04-02 15:11
@marcelfalliere ooo, I would indeed. I'm trying to make each example a self contained app state (with each a little more complicated than the last) so if you're able to do an example with physics that would be amazing!

**Comment by marcelfalliere** [comment] 2022-04-02 17:43
Lol you already implemented climbing ! Nice.

With physics I'm pulling my hair. Not the climbing, but regular movements.

**Comment by richardTingle** [comment] 2022-04-03 10:52
Physics is an interesting one. I think the game that's done this the best is half life alyx. Physics isn't applied to the head at all, but if you put your head anywhere illegal your view gets blanked out. Some physics is applied to the hands in that if you try to put your hands somewhere illegal your in-game hands sort of detach from your real hands (which feels weird in extremes, but the haptic response when you touch something is really good)

**Comment by marcelfalliere** [comment] 2022-04-03 14:12
I haven't played Alyx. I'm playing Into The Radius when there's time :)

So would you mind looking at my fork ? https://github.com/marcelfalliere/TamarinTestBed/tree/physics-movement

I'm trying to synchronise the player capsule (physics) with the real world movement. And well, as you can see, there's a non wanted behaviour when the player moves out of the capsule. 

So when the player is inside, the physics movement driven by analog stick work well. But when he physically moves out of the capsule, I would just like the capsule to follow : it does, but immediatly after that it moves, so the capsule never stops.

Could you please tell me your opinion.

**Comment by richardTingle** [comment] 2022-04-03 16:29
@marcelfalliere Ooo, Into The Radius looks interesting, does it only have continuous movement or does it have teleport style as well? (I have a pretty good head for VR but continuous movement still makes me feel unwell)

I think the problem is that the code assumes it's possible to place the observer at the same position as the capsule, but if the player is physically standing a meter from the play area origin that is impossible (and line 144 tries to enforce that and so leads to the strange behaviour). If you look at the diagram at https://github.com/oneMillionWorlds/Tamarin/wiki/Understanding-the-observer and imagine your player standing at the grey dot there is no way you can make the observer have the same position as the player (and attempting to do so makes the players eyes jump away from their body; as you're experiencing).

I'd ask what your objective is, I'd be trying to make the hands have physics (so you can brush objects aside with your hands etc) but having the player themselves have physics doesn't feel like it has utility; you can't stop the player sticking their head through a wall. I don't use bullet physics so this may not directly translate but I'd perhaps be looking to use some sort of ghost control just to be able to detect when things hit the player but not actually take part in physics beyond that

**Comment by marcelfalliere** [comment] 2022-04-03 17:18
Yes [Into The Radius](https://www.youtube.com/watch?v=1S1EFh2KWxI) has teleport locomotion. I personally don't like it because it breaks the immersion.

Having the player have physics has ton of use cases :
- don't fall through grounds
- fall from building, and hit ground
- jetpack riding
- not going through walls

Fading out the view when player head is through a wall can be achieve with a ghostcontrol indeed.

**Comment by marcelfalliere** [comment] 2022-04-03 17:28
> I'd ask what your objective is, I'd be trying to make the hands have physics (so you can brush objects aside with your hands etc) but having the player themselves have physics doesn't feel like it has utility; you can't stop the player sticking their head through a wall. I don't use bullet physics so this may not directly translate but I'd perhaps be looking to use some sort of ghost control just to be able to detect when things hit the player but not actually take part in physics beyond that

It's Into the radius "classic" movement (not teleportation) gameplay :
- you can move with the thumbstick
- you can move with your body IRL : it moves your in-game body.

I have yet to try Alyx to see how it's done ! But in IntoTheRadius, it's impossible to go through walls (so no fading). The disadvantage is that when you are in game near a wall, a move through it IRL, you don't move in the game. That has nausea-potential, but you just don't do it. Because it's natural. IRL I never try to go through a wall (I'm not David Coperfield :D)

Anyway I like this playstyle. It's immersive !

**Comment by marcelfalliere** [comment] 2022-04-04 17:16
Hey, I found this Unity tutorial that is doing exactly what I want to achieve. Here is a link to the exact part of the video that is relevant : https://youtu.be/5NRTT8Tbmoc?t=719

Anyway, I can't seem to implement the same behaviour in JMonkey. After many tries, I can't make it work. On paper it's easy. Maybe I'm not using the API correctly.

So I'm taking a break from this and get back to it in a few days.

**Comment by richardTingle** [comment] 2022-04-04 19:31
I can see the argument for continuous motion, it is certainly more real. Alas I think a lot of people are like me and get quickly nauseous with it. I'll give Into the radius a go; it looks very interesting.

I think the behaviour you are looking for should be very possible. I think it would have the following behaviours:

- If you walk with the thumb stick over a gap you fall
- If you walk with your feet over a gap you fall
- If you press your face into a wall it feels a bit like your face is pushing the world away from you (to prevent you intersecting the wall
- If you walk up a slope you rise

This would have the following accepted behaviours (i.e. we don't want them but they can't be avoided):
- If you lean over a gap this is interpreted as you stepping into the gap and you fall
- If you lean over a low wall this is interpreted as you pushing your face into it and the world is pushed back.

Assuming that sounds right I'll have a play and see if I can build something with those behaviours. I'll be going on holiday soon so I'll either get to it in the next couple of days or disappear for a couple of weeks.

**Comment by richardTingle** [comment] 2022-04-06 16:42
@marcelfalliere I was able to put something together before I went away. Its not quite as polished as I'd like so its in a separate HardPhysics branch at https://github.com/oneMillionWorlds/TamarinTestBed/tree/HardPhysics

This example has a tall wall that if you "push your face into" the world pushes away (full disclosure I verbally shuddered when that happened). More pleasantly there is a set of stairs and if you walk up or down them (either physically or via the right thumbstick) you raise or fall along with it (and jumping off the end you fall all the way down).

It doesn't currently have teleport based movement, just thumb stick based but with a bit of work I'll get that sorted too (It kind of needs to allow teleporting smoothly up steps which is why it needs a bit more work)

It works on the following principle:

- Every tick there will be a difference between the VR headset calculated feet position and the physics engine calculated feet position. This is corrected either by moving the physics state to correlate with the VR headset or moving the observer such that the VR state is correlated with physics (or some combination of both)
- By default the VR state wins (i.e. the physics state is updated to be where the VR state thinks it should be)
- If over the course of a tick the physics state of the player has **changed** from how it was left then this is a correction (e.g. the player falling, or being pushed) and the observer is moved to compensate for the change (the physics state wins only if the physics engine has moved the player).

I'll try to flesh out the example, make it a bit clear, and merge it into the main branch when I get back from holiday

**Comment by marcelfalliere** [comment] 2022-04-09 16:23
I tested it yesterday, it's pretty nice ! I'll fork it and have my fun with it. If think it can be enhanced so that when your head goes through a wall, it does not jitter. The world should move more smoothly.

I'm working on something else atm.

Have some sweat holidays
